import type { NextPage } from 'next'
import Head from 'next/head'
import Content from '../components/Content'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import styled from 'styled-components'

const Container = styled.div`
  background-color: #DAE0E6;
  text-align:center;
   display:flex;
   flex-direction:column;
   min-height:100vh;
`;

const Home: NextPage = () => {
  return (
    <Container>
      <Navbar />
      <Head>
        <title>Tactablog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/tLogo.jpeg" />
      </Head>
      <Content />
      <Footer />
    </Container>
  )
}

export default Home
